### ISSUE TITLE
gmail

### ISSUE THREAD

**Issue by monalisa62003** [halojoy/ActivateLogin#2]
can i use my hosting webmail for this or do i need to use an actual gmail account, i cant get the details working to send emails out, pls thanks

**Comment by halojoy** [comment]
It should be possible to use your webmail.
As long as you have password for your webmail.

**Comment by monalisa62003** [comment]
hey thanks for replying. im not a very expierenced coder and im more used to sqli. didnt realize it was pdo or else it would be perfect:(
